# Generated by Django 4.1.2 on 2022-12-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javascript', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
