# Generated by Django 4.1.2 on 2022-12-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javascript', '0002_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
