# Generated by Django 4.1.2 on 2022-12-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javascript', '0003_alter_animal_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
