# Generated by Django 3.1.5 on 2022-01-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_it',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
