# Generated by Django 3.1.5 on 2022-01-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_it', '0004_auto_20220114_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_it',
            name='cookies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ask_it',
            name='upvotes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reply',
            name='cookies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='upvotes',
            field=models.IntegerField(default=1),
        ),
    ]
