# Generated by Django 3.1.5 on 2022-02-15 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask_it', '0006_cookie_jar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvoted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted_questions', models.ManyToManyField(blank=True, to='ask_it.Ask_it')),
                ('upvoted_reply', models.ManyToManyField(blank=True, to='ask_it.Reply')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
