# Generated by Django 3.1.5 on 2022-02-19 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask_it', '0007_upvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvoted',
            name='upvoted_reply',
        ),
        migrations.RemoveField(
            model_name='upvoted',
            name='upvoted_questions',
        ),
        migrations.AddField(
            model_name='upvoted',
            name='upvoted_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_it.ask_it'),
        ),
        migrations.AlterField(
            model_name='upvoted',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
