# Generated by Django 4.1.dev20220328112539 on 2022-04-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_it', '0010_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='QuestionImage',
        ),
    ]
