# Generated by Django 4.1.dev20220328112539 on 2022-04-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_it', '0011_rename_post_questionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionimage',
            name='title',
        ),
        migrations.AddField(
            model_name='ask_it',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ask_it',
            name='img_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
