# Generated by Django 4.1.dev20220328112539 on 2022-04-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_it', '0012_remove_questionimage_title_ask_it_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask_it',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ask_it',
            old_name='img_caption',
            new_name='image_caption',
        ),
    ]
