# Generated by Django 4.1.2 on 2022-12-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_game', models.BooleanField(default=True)),
                ('health', models.IntegerField(default=5)),
                ('bedroom_key', models.BooleanField(default=False)),
                ('front_key', models.BooleanField(default=False)),
                ('jack_found', models.BooleanField(default=False)),
            ],
        ),
    ]
