# Generated by Django 3.1.5 on 2021-09-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0033_auto_20210131_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
