# Generated by Django 3.1.5 on 2021-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0039_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graffiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
