# Generated by Django 3.1.5 on 2021-10-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0041_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food',
            new_name='name',
        ),
    ]
