# Generated by Django 3.1.5 on 2021-11-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0045_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
