# Generated by Django 3.1.5 on 2021-11-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0049_award_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
