# Generated by Django 3.1.5 on 2021-11-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0051_auto_20211119_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='city',
        ),
        migrations.AlterField(
            model_name='nbateam',
            name='worth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
