# Generated by Django 3.1.5 on 2021-11-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0053_nbateam_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='city',
        ),
    ]
