# Generated by Django 3.1.5 on 2021-11-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0057_auto_20211119_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='city',
            field=models.ForeignKey(default=224, on_delete=django.db.models.deletion.CASCADE, to='exercises.city'),
        ),
    ]
