# Generated by Django 3.1.5 on 2021-11-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0058_nbateam_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=83, on_delete=django.db.models.deletion.CASCADE, to='exercises.country'),
        ),
    ]
