# Generated by Django 3.1.5 on 2021-11-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0060_auto_20211120_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
